name: scanaware
description: ScanAware mobile application
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+9
  google_mlkit_barcode_scanning: ^0.12.0
  permission_handler: ^11.1.0
  http: ^1.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
